_graphics_config:
  figure_config:
    mass_color_-: '#000000'
    mass_height_px: 10
    mass_width_px: 100
    rod_a_color_-: '#00dd00'
    rod_a_thickness_px: 4
    rod_b_color_-: '#0000dd'
    rod_b_thickness_px: 4
    rod_section_ratio_-: 1
  figure_pos_y_px: 20
  figure_x_scale_-: 1
_sim_gui_config:
  bg_color_-: '#efefef'
  def_win_height_px: 1080
  def_win_width_px: 1920
  open_on_monitor_id: 1
geometry_config:
  double_pendulum: true
  rod_a_length_m: 10
  rod_b_length_m: 1
  rod_a_m/l_ratio_kg/m: 1
  rod_b_m/l_ratio_kg/m: 1
  _mass_visibile: true
  _rod_a_visibile: true
  rod_b_visibile: true
  infinite_vertical_space: true
  fullscreen: true
input_config:
  mouse_osl_move_mm: 11
  scale_rotation_-: 1
  scale_x_axis_-: 1000
  screen_width_px: 1920
  screen_width_m: 0.52
simulation_config:
  _simulation_title: M_1_ctrl
  _maximum_theta1_rad: 1.5
  _sample_rate_s: 0.0166666667
  _open_on_monitor_id: 0
  gravitational_force_m/s^2: 9.81
  model_initial_dof_values_rad: -0.01, 0
  _num_method_-: rk4
  time_delay_s: 0
  constant_rod_length: true
  rod_a_dl_m: 0.1
  rod_a_dt_s: 2.0
  rod_b_dl_m: 0
  rod_b_dt_s: 0
PD_control:
  PD_control_on: true
  optimal_control_calc_method: custom
  k1_-: 15.789474
  k2_-: 0
  k3_-: 15.789474
  k4_-: 0
  time_delay_s: 0.2
  enable_mouse_input: true
  _desired_phi_rad: 0
  _LQR_Q:
  - 50
  - 20
  - 700
  - 700
  _LQR_R: 1
